name: Deploying To Firebase Hosting

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: npm install

      - name: Building The Project
        run: npm run build:prod

      - name: Installing Firebase
        run: npm install -g firebase

      - name: Installing Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploying To Firebase Hosting
        run: firebase deploy --project cinema--page --token=${{ secrets.FIREBASE_TOKEN }}
